/**
 * Database Tests: Prisma Operations
 * Tests for database models, relationships, and queries
 */

import { 
  createMockPrismaClient, 
  mockProject, 
  mockPhase, 
  mockAgent, 
  mockAgentExecution,
  mockPortfolio,
  mockPosition,
  mockTransaction,
  mockERVDecision,
  mockERVPolicy,
  mockHumanApproval,
  mockAuditLog,
  mockUser,
  mockFinancialData,
} from '../utils/test-utils';

const mockDb = createMockPrismaClient();

// ============================================
// Project Model Tests
// ============================================
describe('Project Model', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  describe('Create Operations', () => {
    test('should create project with required fields', async () => {
      const project = mockProject();
      mockDb.project.create.mockResolvedValue(project);

      const result = await mockDb.project.create({
        data: {
          name: 'Test Project',
          status: 'draft',
          mode: 'simulation',
        },
      });

      expect(result.name).toBe('Test Project');
      expect(mockDb.project.create).toHaveBeenCalled();
    });

    test('should create project with all optional fields', async () => {
      const project = mockProject({
        description: 'Full description',
        createdBy: 'user_123',
        startedAt: new Date().toISOString(),
      });

      mockDb.project.create.mockResolvedValue(project);

      const result = await mockDb.project.create({
        data: {
          name: 'Test Project',
          description: 'Full description',
          status: 'running',
          mode: 'live',
          createdBy: 'user_123',
        },
      });

      expect(result.description).toBe('Full description');
    });

    test('should auto-generate project ID', async () => {
      const project = mockProject();
      mockDb.project.create.mockResolvedValue(project);

      await mockDb.project.create({
        data: { name: 'Test' },
      });

      // ID should be generated by Prisma
      expect(mockDb.project.create).toHaveBeenCalled();
    });

    test('should set timestamps automatically', async () => {
      const now = new Date();
      const project = mockProject({
        createdAt: now.toISOString(),
        updatedAt: now.toISOString(),
      });

      mockDb.project.create.mockResolvedValue(project);

      const result = await mockDb.project.create({
        data: { name: 'Test' },
      });

      expect(result.createdAt).toBeDefined();
      expect(result.updatedAt).toBeDefined();
    });
  });

  describe('Read Operations', () => {
    test('should find project by ID', async () => {
      const project = mockProject();
      mockDb.project.findUnique.mockResolvedValue(project);

      const result = await mockDb.project.findUnique({
        where: { id: 'project_test' },
      });

      expect(result).not.toBeNull();
    });

    test('should return null for non-existent project', async () => {
      mockDb.project.findUnique.mockResolvedValue(null);

      const result = await mockDb.project.findUnique({
        where: { id: 'nonexistent' },
      });

      expect(result).toBeNull();
    });

    test('should find many projects', async () => {
      const projects = [mockProject(), mockProject({ id: 'project_2' })];
      mockDb.project.findMany.mockResolvedValue(projects);

      const result = await mockDb.project.findMany();

      expect(result).toHaveLength(2);
    });

    test('should include related phases', async () => {
      const project = {
        ...mockProject(),
        phases: [mockPhase(), mockPhase({ id: 'phase_2' })],
      };

      mockDb.project.findUnique.mockResolvedValue(project);

      const result = await mockDb.project.findUnique({
        where: { id: 'project_test' },
        include: { phases: true },
      });

      expect(result?.phases).toHaveLength(2);
    });

    test('should include portfolio with positions', async () => {
      const project = {
        ...mockProject(),
        portfolio: {
          ...mockPortfolio(),
          positions: [mockPosition(), mockPosition({ id: 'position_2' })],
        },
      };

      mockDb.project.findUnique.mockResolvedValue(project);

      const result = await mockDb.project.findUnique({
        where: { id: 'project_test' },
        include: { portfolio: { include: { positions: true } } },
      });

      expect(result?.portfolio?.positions).toHaveLength(2);
    });

    test('should filter by status', async () => {
      const runningProjects = [mockProject({ status: 'running' })];
      mockDb.project.findMany.mockResolvedValue(runningProjects);

      await mockDb.project.findMany({
        where: { status: 'running' },
      });

      expect(mockDb.project.findMany).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { status: 'running' },
        })
      );
    });

    test('should order by creation date', async () => {
      mockDb.project.findMany.mockResolvedValue([]);

      await mockDb.project.findMany({
        orderBy: { createdAt: 'desc' },
      });

      expect(mockDb.project.findMany).toHaveBeenCalledWith(
        expect.objectContaining({
          orderBy: { createdAt: 'desc' },
        })
      );
    });
  });

  describe('Update Operations', () => {
    test('should update project status', async () => {
      const updated = mockProject({ status: 'running' });
      mockDb.project.update.mockResolvedValue(updated);

      const result = await mockDb.project.update({
        where: { id: 'project_test' },
        data: { status: 'running' },
      });

      expect(result.status).toBe('running');
    });

    test('should update project timestamps', async () => {
      const startedAt = new Date().toISOString();
      const updated = mockProject({ status: 'running', startedAt });
      mockDb.project.update.mockResolvedValue(updated);

      await mockDb.project.update({
        where: { id: 'project_test' },
        data: { 
          status: 'running',
          startedAt: new Date(startedAt),
        },
      });

      expect(mockDb.project.update).toHaveBeenCalled();
    });

    test('should complete project', async () => {
      const completedAt = new Date().toISOString();
      const updated = mockProject({ 
        status: 'completed', 
        completedAt 
      });
      mockDb.project.update.mockResolvedValue(updated);

      const result = await mockDb.project.update({
        where: { id: 'project_test' },
        data: { 
          status: 'completed',
          completedAt: new Date(completedAt),
        },
      });

      expect(result.status).toBe('completed');
    });
  });

  describe('Delete Operations', () => {
    test('should delete project', async () => {
      mockDb.project.delete.mockResolvedValue(mockProject());

      await mockDb.project.delete({
        where: { id: 'project_test' },
      });

      expect(mockDb.project.delete).toHaveBeenCalled();
    });

    test('should cascade delete phases', async () => {
      // Prisma handles cascade via schema
      mockDb.project.delete.mockResolvedValue(mockProject());

      await mockDb.project.delete({
        where: { id: 'project_test' },
      });

      // Phases should be deleted via cascade
      expect(mockDb.project.delete).toHaveBeenCalled();
    });
  });

  describe('Count Operations', () => {
    test('should count total projects', async () => {
      mockDb.project.count.mockResolvedValue(10);

      const count = await mockDb.project.count();

      expect(count).toBe(10);
    });

    test('should count by status', async () => {
      mockDb.project.count.mockResolvedValue(3);

      const count = await mockDb.project.count({
        where: { status: 'running' },
      });

      expect(count).toBe(3);
    });
  });
});

// ============================================
// Phase Model Tests
// ============================================
describe('Phase Model', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  test('should create phase with project relation', async () => {
    const phase = mockPhase();
    mockDb.phase.create.mockResolvedValue(phase);

    const result = await mockDb.phase.create({
      data: {
        projectId: 'project_test',
        name: 'research',
        displayName: 'Research',
        order: 0,
        status: 'pending',
      },
    });

    expect(result.projectId).toBe('project_test');
  });

  test('should create multiple phases', async () => {
    mockDb.phase.createMany.mockResolvedValue({ count: 5 });

    const result = await mockDb.phase.createMany({
      data: [
        { projectId: 'project_test', name: 'research', displayName: 'Research', order: 0, status: 'pending' },
        { projectId: 'project_test', name: 'analysis', displayName: 'Analysis', order: 1, status: 'pending' },
      ],
    });

    expect(result.count).toBe(5);
  });

  test('should order phases correctly', async () => {
    const phases = [
      mockPhase({ name: 'research', order: 0 }),
      mockPhase({ name: 'analysis', order: 1 }),
    ];
    mockDb.phase.findMany.mockResolvedValue(phases);

    const result = await mockDb.phase.findMany({
      where: { projectId: 'project_test' },
      orderBy: { order: 'asc' },
    });

    expect(result[0].order).toBeLessThan(result[1].order);
  });

  test('should update phase status', async () => {
    const updated = mockPhase({ status: 'completed' });
    mockDb.phase.update.mockResolvedValue(updated);

    const result = await mockDb.phase.update({
      where: { id: 'phase_test' },
      data: { status: 'completed' },
    });

    expect(result.status).toBe('completed');
  });

  test('should update many phases', async () => {
    mockDb.phase.updateMany.mockResolvedValue({ count: 3 });

    const result = await mockDb.phase.updateMany({
      where: { projectId: 'project_test' },
      data: { status: 'pending' },
    });

    expect(result.count).toBe(3);
  });
});

// ============================================
// Agent Model Tests
// ============================================
describe('Agent Model', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  test('should create agent with unique name', async () => {
    const agent = mockAgent();
    mockDb.agent.create.mockResolvedValue(agent);

    const result = await mockDb.agent.create({
      data: {
        name: 'sentinel',
        displayName: 'Sentinel',
        description: 'Market surveillance',
      },
    });

    expect(result.name).toBe('sentinel');
  });

  test('should find agent by name', async () => {
    const agent = mockAgent({ name: 'oracle' });
    mockDb.agent.findUnique.mockResolvedValue(agent);

    const result = await mockDb.agent.findUnique({
      where: { name: 'oracle' },
    });

    expect(result?.name).toBe('oracle');
  });

  test('should update agent configuration', async () => {
    const updated = mockAgent({ config: '{"threshold": 0.8}' });
    mockDb.agent.update.mockResolvedValue(updated);

    const result = await mockDb.agent.update({
      where: { id: 'agent_test' },
      data: { config: '{"threshold": 0.8}' },
    });

    expect(result.config).toBe('{"threshold": 0.8}');
  });

  test('should enable/disable agent', async () => {
    const disabled = mockAgent({ enabled: false });
    mockDb.agent.update.mockResolvedValue(disabled);

    const result = await mockDb.agent.update({
      where: { id: 'agent_test' },
      data: { enabled: false },
    });

    expect(result.enabled).toBe(false);
  });
});

// ============================================
// Portfolio Model Tests
// ============================================
describe('Portfolio Model', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  test('should create portfolio for project', async () => {
    const portfolio = mockPortfolio();
    mockDb.portfolio.create.mockResolvedValue(portfolio);

    const result = await mockDb.portfolio.create({
      data: {
        projectId: 'project_test',
        cash: 100000,
        totalValue: 100000,
      },
    });

    expect(result.projectId).toBe('project_test');
  });

  test('should update portfolio value', async () => {
    const updated = mockPortfolio({ totalValue: 150000 });
    mockDb.portfolio.update.mockResolvedValue(updated);

    const result = await mockDb.portfolio.update({
      where: { projectId: 'project_test' },
      data: { totalValue: 150000 },
    });

    expect(result.totalValue).toBe(150000);
  });

  test('should track P&L', async () => {
    const updated = mockPortfolio({ 
      dayPnL: 5000, 
      totalPnL: 15000 
    });
    mockDb.portfolio.update.mockResolvedValue(updated);

    const result = await mockDb.portfolio.update({
      where: { projectId: 'project_test' },
      data: { dayPnL: 5000, totalPnL: 15000 },
    });

    expect(result.dayPnL).toBe(5000);
    expect(result.totalPnL).toBe(15000);
  });

  test('should store risk metrics', async () => {
    const updated = mockPortfolio({
      sharpeRatio: 1.5,
      var95: 5000,
      maxDrawdown: 0.15,
    });
    mockDb.portfolio.update.mockResolvedValue(updated);

    const result = await mockDb.portfolio.update({
      where: { projectId: 'project_test' },
      data: {
        sharpeRatio: 1.5,
        var95: 5000,
        maxDrawdown: 0.15,
      },
    });

    expect(result.sharpeRatio).toBe(1.5);
    expect(result.var95).toBe(5000);
    expect(result.maxDrawdown).toBe(0.15);
  });
});

// ============================================
// Position Model Tests
// ============================================
describe('Position Model', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  test('should create position', async () => {
    const position = mockPosition();
    mockDb.position.create.mockResolvedValue(position);

    const result = await mockDb.position.create({
      data: {
        portfolioId: 'portfolio_test',
        symbol: 'AAPL',
        quantity: 100,
        avgCost: 150.00,
      },
    });

    expect(result.symbol).toBe('AAPL');
    expect(result.quantity).toBe(100);
  });

  test('should update position quantity', async () => {
    const updated = mockPosition({ quantity: 200 });
    mockDb.position.update.mockResolvedValue(updated);

    const result = await mockDb.position.update({
      where: { id: 'position_test' },
      data: { quantity: 200 },
    });

    expect(result.quantity).toBe(200);
  });

  test('should track unrealized P&L', async () => {
    const updated = mockPosition({ unrealizedPnL: 500 });
    mockDb.position.update.mockResolvedValue(updated);

    const result = await mockDb.position.update({
      where: { id: 'position_test' },
      data: { unrealizedPnL: 500 },
    });

    expect(result.unrealizedPnL).toBe(500);
  });
});

// ============================================
// Transaction Model Tests
// ============================================
describe('Transaction Model', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  test('should create buy transaction', async () => {
    const transaction = mockTransaction({ type: 'buy' });
    mockDb.transaction.create.mockResolvedValue(transaction);

    const result = await mockDb.transaction.create({
      data: {
        portfolioId: 'portfolio_test',
        symbol: 'AAPL',
        type: 'buy',
        quantity: 100,
        price: 150.00,
        total: 15000,
        executedBy: 'oracle',
      },
    });

    expect(result.type).toBe('buy');
    expect(result.total).toBe(15000);
  });

  test('should create sell transaction', async () => {
    const transaction = mockTransaction({ type: 'sell' });
    mockDb.transaction.create.mockResolvedValue(transaction);

    const result = await mockDb.transaction.create({
      data: {
        portfolioId: 'portfolio_test',
        symbol: 'AAPL',
        type: 'sell',
        quantity: 50,
        price: 160.00,
        total: 8000,
        executedBy: 'vector',
      },
    });

    expect(result.type).toBe('sell');
  });

  test('should link to ERV decision', async () => {
    const transaction = mockTransaction({ ervDecision: 'erv_123' });
    mockDb.transaction.create.mockResolvedValue(transaction);

    const result = await mockDb.transaction.create({
      data: {
        portfolioId: 'portfolio_test',
        symbol: 'AAPL',
        type: 'buy',
        quantity: 100,
        price: 150.00,
        total: 15000,
        executedBy: 'oracle',
        ervDecision: 'erv_123',
      },
    });

    expect(result.ervDecision).toBe('erv_123');
  });
});

// ============================================
// Audit Log Model Tests
// ============================================
describe('AuditLog Model', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  test('should create audit log entry', async () => {
    const auditLog = mockAuditLog({
      actor: 'oracle',
      action: 'execute_trade',
    });
    mockDb.auditLog.create.mockResolvedValue(auditLog);

    const result = await mockDb.auditLog.create({
      data: {
        projectId: 'project_test',
        actor: 'oracle',
        action: 'execute_trade',
        resource: 'portfolio',
        details: '{"symbol": "AAPL"}',
        hash: 'abc123',
      },
    });

    expect(result.actor).toBe('oracle');
    expect(result.action).toBe('execute_trade');
  });

  test('should link to previous log entry', async () => {
    const auditLog = mockAuditLog({ previousHash: 'prev_hash_123' });
    mockDb.auditLog.create.mockResolvedValue(auditLog);

    const result = await mockDb.auditLog.create({
      data: {
        projectId: 'project_test',
        actor: 'oracle',
        action: 'execute_trade',
        resource: 'portfolio',
        details: '{}',
        hash: 'new_hash',
        previousHash: 'prev_hash_123',
      },
    });

    expect(result.previousHash).toBe('prev_hash_123');
  });

  test('should include IP address and user agent', async () => {
    const auditLog = mockAuditLog({
      ipAddress: '192.168.1.1',
      userAgent: 'Mozilla/5.0',
    });
    mockDb.auditLog.create.mockResolvedValue(auditLog);

    const result = await mockDb.auditLog.create({
      data: {
        projectId: 'project_test',
        actor: 'oracle',
        action: 'test',
        resource: 'test',
        details: '{}',
        hash: 'hash',
        ipAddress: '192.168.1.1',
        userAgent: 'Mozilla/5.0',
      },
    });

    expect(result.ipAddress).toBe('192.168.1.1');
    expect(result.userAgent).toBe('Mozilla/5.0');
  });
});

// ============================================
// User Model Tests
// ============================================
describe('User Model', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  test('should create user with email', async () => {
    const user = mockUser();
    mockDb.user.create.mockResolvedValue(user);

    const result = await mockDb.user.create({
      data: {
        email: 'test@example.com',
        name: 'Test User',
        role: 'viewer',
      },
    });

    expect(result.email).toBe('test@example.com');
  });

  test('should enforce unique email', async () => {
    const user = mockUser({ email: 'unique@example.com' });
    mockDb.user.create.mockResolvedValue(user);

    await mockDb.user.create({
      data: {
        email: 'unique@example.com',
        name: 'Test User',
      },
    });

    expect(mockDb.user.create).toHaveBeenCalled();
  });

  test('should assign role', async () => {
    const admin = mockUser({ role: 'admin' });
    mockDb.user.create.mockResolvedValue(admin);

    const result = await mockDb.user.create({
      data: {
        email: 'admin@example.com',
        name: 'Admin User',
        role: 'admin',
      },
    });

    expect(result.role).toBe('admin');
  });

  test('should generate API key', async () => {
    const user = mockUser({ apiKey: 'sk_test_12345' });
    mockDb.user.update.mockResolvedValue(user);

    const result = await mockDb.user.update({
      where: { id: 'user_test' },
      data: { apiKey: 'sk_test_12345' },
    });

    expect(result.apiKey).toBe('sk_test_12345');
  });
});

// ============================================
// Financial Data Model Tests
// ============================================
describe('FinancialData Model', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  test('should cache financial data', async () => {
    const data = mockFinancialData();
    mockDb.financialData.create.mockResolvedValue(data);

    const result = await mockDb.financialData.create({
      data: {
        symbol: 'AAPL',
        dataType: 'price',
        source: 'alpha_vantage',
        data: '{"price": 150.00}',
        expiresAt: new Date(Date.now() + 3600000),
      },
    });

    expect(result.symbol).toBe('AAPL');
    expect(result.dataType).toBe('price');
  });

  test('should check expiration', async () => {
    const data = mockFinancialData({
      fetchedAt: new Date(Date.now() - 7200000).toISOString(),
      expiresAt: new Date(Date.now() - 3600000).toISOString(),
    });
    mockDb.financialData.findFirst.mockResolvedValue(data);

    const result = await mockDb.financialData.findFirst({
      where: {
        symbol: 'AAPL',
        dataType: 'price',
      },
    });

    const isExpired = result && new Date(result.expiresAt) < new Date();
    expect(isExpired).toBe(true);
  });

  test('should enforce unique symbol-type-source', async () => {
    mockDb.financialData.upsert.mockResolvedValue(mockFinancialData());

    await mockDb.financialData.upsert({
      where: {
        symbol_dataType_source: {
          symbol: 'AAPL',
          dataType: 'price',
          source: 'alpha_vantage',
        },
      },
      update: { data: '{"price": 155.00}' },
      create: {
        symbol: 'AAPL',
        dataType: 'price',
        source: 'alpha_vantage',
        data: '{"price": 155.00}',
        expiresAt: new Date(Date.now() + 3600000),
      },
    });

    expect(mockDb.financialData.upsert).toHaveBeenCalled();
  });
});

// ============================================
// Transaction Tests
// ============================================
describe('Database Transactions', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  test('should execute transaction callback', async () => {
    mockDb.$transaction.mockImplementation(async (fn) => {
      return fn(mockDb);
    });

    await mockDb.$transaction(async (tx) => {
      await tx.project.create({ data: { name: 'Test' } });
      await tx.phase.createMany({ data: [] });
    });

    expect(mockDb.$transaction).toHaveBeenCalled();
  });

  test('should rollback on error', async () => {
    mockDb.$transaction.mockRejectedValue(new Error('Transaction failed'));

    await expect(
      mockDb.$transaction(async () => {
        throw new Error('Rollback');
      })
    ).rejects.toThrow();
  });
});
