// NOTE: This file is autogenerated. Do not edit manually.
#pragma once
#include <libdragon.h>

namespace P64::Assets
{
  consteval uint32_t getAssetIndex(std::string_view path)
  {
    {{ASSET_MAP}}
    assertf(false, "Asset unknown!");
  }
}

consteval uint32_t operator"" _asset(const char *str, size_t len) {
  return P64::Assets::getAssetIndex(std::string_view{str, len});
}
