// NOTE: This file is autogenerated. Do not edit manually.
#pragma once
#include <libdragon.h>
#include <string_view>

namespace P64::SceneManager
{
  consteval uint16_t getSceneIdx(std::string_view path)
  {
    {{SCENE_MAP}}
    assertf(false, "Scene unknown!");
  }

  extern const char* SCENE_NAMES[{{SCENE_COUNT}}];
}

consteval uint16_t operator"" _scene(const char *str, size_t len) {
  return P64::SceneManager::getSceneIdx(std::string_view{str, len});
}
