-- Create tables
CREATE TABLE IF NOT EXISTS jobs (
    id TEXT PRIMARY KEY,
    business_name TEXT,
    vertical TEXT,
    category TEXT,
    block_type TEXT,
    start_window TEXT,
    location TEXT,
    required_skills JSONB,
    status TEXT,
    payout NUMERIC,
    charge NUMERIC,
    created_at TIMESTAMPTZ,
    checklist JSONB,
    headcount INTEGER,
    bill_rate NUMERIC,
    pay_rate NUMERIC,
    markup NUMERIC,
    hours_per_shift NUMERIC,
    duration_shifts INTEGER,
    location_name TEXT,
    shift_start_time TEXT,
    shift_end_time TEXT,
    recruiter_id TEXT,
    recruiter_name TEXT,
    branch_name TEXT,
    state_code TEXT,
    invoice_term_days INTEGER
);

CREATE TABLE IF NOT EXISTS candidates (
    id TEXT PRIMARY KEY,
    name TEXT,
    email TEXT,
    phone TEXT,
    skills JSONB,
    verticals JSONB,
    total_earned NUMERIC,
    status TEXT,
    background_check_status TEXT,
    esign_status TEXT,
    verified_credentials JSONB,
    weekly_availability JSONB,
    shift_preferences JSONB,
    pay_option TEXT,
    direct_deposit_detail JSONB,
    profile_updated BOOLEAN,
    state_code TEXT,
    recruiter_name TEXT,
    branch_name TEXT,
    performance_score INTEGER,
    time_to_onboard_days INTEGER,
    no_show_count INTEGER,
    is_redeployed BOOLEAN,
    documents JSONB,
    messages JSONB,
    reliability_score INTEGER,
    attendance_rate INTEGER,
    punctuality_rate INTEGER,
    completion_rate INTEGER,
    client_rating_class TEXT
);
